---
name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
      # Secret Scanning Step
       - name: Run Secret Scanning
         run: |
           docker run --rm -v ${{ github.workspace }}:/repo zricethezav/gitleaks:v8.2.7 detect --source=/repo --report-format=json --report-path=/repo/gitleaks_report.json

       - name: Add Docker's GPG key and repository
         run: >
           sudo apt-get update

           sudo apt-get install -y ca-certificates curl

           sudo install -m 0755 -d /etc/apt/keyrings

           sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc

           sudo chmod a+r /etc/apt/keyrings/docker.asc

           # Add Docker repository to Apt sources

           echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

           sudo apt-get update
       - name: Install Docker
         run: >
           sudo apt-get install -y docker-ce docker-ce-cli containerd.io
           docker-buildx-plugin docker-compose-plugin
       - name: Check if Docker is working
         run: sudo docker run hello-world
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
       - name: Check docker is working fine
         run: docker ps
      # Source Composition Analysis (SCA) using npm to install Snyk
       - name: Install Snyk CLI
         run: |
           npm install -g snyk

       # Authenticate with Snyk using the API token
       - name: Authenticate with Snyk
         run: snyk auth ${{ secrets.SNYK_TOKEN }}

       # Run SCA (Snyk)
       - name: Run SCA with Snyk
         run: snyk test --all-projects

       # Static Application Security Testing (SAST)
       - name: Run SAST (SonarQube as an example)
         run: |
           curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
           unzip sonar-scanner.zip -d sonar-scanner
           ./sonar-scanner/bin/sonar-scanner \
             -Dsonar.projectKey=my-project-key \
             -Dsonar.sources=. \
             -Dsonar.host.url=https://sonarcloud.io \
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
       - name: Build Docker image
         run: |
           docker build -t sanginimiharia2002/simple-webapp .
       - name: Push Docker image
         run: |
           docker push sanginimiharia2002/simple-webapp

   deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      #- name: SSh to ec2 with minkube
      #  run: ssh -i ${{secrets.PEM_FILE}} ubuntu@51.20.98.144 -y

      - name: Create SSH key file
        run: |
          echo "${{ secrets.PEM_FILE }}" > ~/my_key.pem
          chmod 600 ~/my_key.pem

      - name: SSH to EC2 with Minikube
        run: ssh -i ~/my_key.pem -o StrictHostKeyChecking=no ubuntu@51.20.98.144

      - name: Clone project
        run: git clone https://github.com/SanginiMiharia/Project.git

      - name: ls
        run: ls -la 

      - name: Go to Simple-webapp
        run: cd simple-webapp

      - name: Pull docker image
        run: docker pull sanginimiharia2002/simple-webapp

      - name: Start minikube
        run: minikube start

      - name: Download Helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm
          
      - name: Deploy to Kubernetes with Helm
        run: |
          helm upgrade --install simple-webapp ./helm-chart \
            --set image.repository=sanginimiharia2002/simple-webapp \
            --set image.tag=latest
       # Dynamic Application Security Testing (DAST)
      # Assuming OWASP ZAP is installed and configured on your EC2 instance.
      - name: Run DAST Scan with OWASP ZAP 
        run: zap-cli quick-scan --self-contained --spider http://your-app-url.com

            